[package]
name = "nbabel"
version = "0.2.0"
edition = "2018"

[dependencies]
wide = "^0.6"
threadpool = "^1.8"
num_cpus = "1.13"

[[bin]]
name = "nbabel"
path = "src/main.rs"

[lib]
name = "nbabel_lib"
path = "src/lib.rs"

[features]
std = []