[package]
name = "nbabel"
version = "0.1.0"
edition = "2018"

[dependencies]
wide = { version = "0.6.4"}

[[bin]]
name = "nbabel"
path = "src/main.rs"

[lib]
name = "nbabel_lib"
path = "src/lib.rs"

[features]
std = []